baseURL = 'https://1garo.io/'
languageCode = 'en-us'
title = '1garo'
theme = 'yinyang'
enableRobotsTXT = true
canonifyURLs = false


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = 'tango'
    tabWidth = 2

[permalinks]
  post = 'blog/:title/'

[author]
name = '1garo'
homepage = 'https://github.com/1garo'

[params]
description = 'writing my thoughts out loud'
headTitle = "1garo's blog"
mainSections = ['posts']
twitterCards = true
lazyImage = true

[[params.socials]]
name = 'github'
link = 'https://github.com/1garo'
