baseURL = 'https://1garo.github.io/'
title = "1garo's blog"
languageCode = "en-us"
theme = "typo"

[taxonomies]
tag = 'tags'

[markup]
[markup.highlight]
style = 'bw'

# Configuration Features
[params]
# Math mode
math = true
theme = 'auto'
colorPalette = 'default'
hideHeader = true
breadcrumbs = true
showFooter = false

# Intro on main page, content in markdown, if you omit title or content the other can be displayed
#homeIntro = true
#homeIntroTitle = "Hi!"
homeIntroContent = """
Join me on this journey on how I think about software engineering (and other things).
"""


# Collection to display on home page:
# in this case we would display content/posts pages
homeCollectionTitle = 'Posts'
homeCollection = 'post'

# Pagination size across all website, this is the same for homepage and single list page
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

[[params.social]]
name = "github"                 # Font Awesome icon class
url = "http://github.com/1garo" # Link to associate with icon (http://, https://, mailto:)
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/alevardai"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/post"

[[params.menu]]
name = "resume"
url = "/carrer"
